apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-{{ .Values.appName }}
  labels:
   {{- include "common.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: 418272784676.dkr.ecr.us-east-1.amazonaws.com/roboshop-{{ .Values.appName }}:{{ .Values.COMMIT_ID }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              name: app
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}
          readinessProbe:
            httpGet:
              path: /health
              port: app
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: app
            initialDelaySeconds: 5
            periodSeconds: 5
