{{ if .Values.schema.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-job
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}-job
  dataFrom:
    - extract:
        key: {{ .Values.appName }}-job
{{ end }}