apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "common.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}